### ISSUE TITLE
Don't re enable disabled plugins on startup

### ISSUE THREAD

**Issue by NepNep21** [lambda-client/lambda#216]
**Is your feature request related to a problem? Please describe.**
It's annoying to not be able to properly disable a plugin

**Describe the solution you'd like**
Add a setting (automatically toggled when you click a plugin button) that allows plugins to not be loaded if they were disabled previously

**Describe alternatives you've considered**
Renaming unwanted plugins to <name>.jar.disabled

**Comment by huddy987** [comment]
It seems that this should be the default setting
