### ISSUE TITLE
huge biug

### ISSUE THREAD

**Issue by swpq** [lambda-client/lambda#249]
**Describe the bug**

client Kami skid
**To Reproduce**

run the client in recaf

**Expected behavior**

not Kami skid
**Debug info**

**Additional context / media**

**Comment by mmvanheusden** [comment]
Lambda isn't a skid but a continuation of KAMI blue

**Comment by ToxicAven** [comment]
[swpq/plateau-client](https://github.com/swpq/plateau-client)

> My client that I made
> me/zeroeightysix/kami

Please keep the issues clear of unnecessary spam.

**Comment by swpq** [comment]
Who do you think you're talking to buddy. Do you even know who I am???? The amount of pure DISRESPECT. Screw off, newgen!

**Comment by swpq** [comment]
> Lambda isn't a skid but a continuation of KAMI blue

🐀 🐁

**Comment by mmvanheusden** [comment]
> > Lambda isn't a skid but a continuation of KAMI blue
> 
> 🐀 🐁

you clearly don't understand how open-source works

**Comment by huddy987** [comment]
@swpq not productive. Future troll comments/issues will result in you being banned
