### ISSUE TITLE
not adding friends when using the ;friend add command

### ISSUE THREAD

**Issue by adityaavard** [lambda-client/lambda#392]
I was in my clan when they made an announcement to add everyone in the clan I typed in all the names but when I I used ;friend list it 
did not say the names the only names that come up are the middle click friends

**Comment by CozyMeli-gitv2** [comment]
Unable to reproduce. 

Make sure you are running the correct command, ";friend add [InsertUsernameHere]!

Please let me know if the correct command does not work. Thank you for submitting an issue!
