### ISSUE TITLE
Max Timer Speed

### ISSUE THREAD

**Issue by DummyPotato** [lambda-client/lambda#471]
**Is your enhancement request related to a problem? Please describe.**
No
**Describe the solution you'd like in order to enchance your experience.**
Be able to change max timer speed with commands or something like that.

**Describe alternatives you've considered**
None

**Additional context**
Nah

**Comment by Avanatiker** [comment]
`;set timer ticks 10`

![image](https://user-images.githubusercontent.com/8580605/222342106-d337d240-e5bd-415f-ab1d-3a9770680be1.png)
