### ISSUE TITLE
Auto Sorter lol

### ISSUE THREAD

**Issue by anhtlauncher** [lambda-client/lambda#486]
**Is your feature request related to a problem? Please elaborate.**

not a problem bruh
**Describe the solution or feature you'd like implemented.**

nah just deobf pyro and skid lmfao 🤡
**Describe alternatives you've considered.**

or try deobf new rusher 💀 
**Additional context:**

like this https://www.youtube.com/watch?v=lo-h-aQjIh4
or this https://youtu.be/_q5YvDdZ8I4

**Comment by ToxicAven** [comment]
No
