### ISSUE TITLE
[1.20.x] [All] Bug: Setting reload

### ISSUE THREAD

**Issue by Avanatiker** [lambda-client/lambda#77]
### What happened?

This coroutine crash happens when e.g a block was added to the "Blocks" setting of the BlockESP.
Then reload the settings

### What should have happened?

x

### Version

1.0.0

### Log Output

https://mclo.gs/l4ExOzm

Edit: Moved crash log to mclo.gs

**Comment by emyfops** [comment]
I have a completely different crash when reproducing the issue

https://mclo.gs/t2HjWAy

**Comment by emyfops** [comment]
I could not reproduce this issue in master, can you confirm @Avanatiker ?
